### ISSUE TITLE
how to create signinUser in Mutation and SigninUserInput, SigninPayload type in schema.graphql

### ISSUE THREAD

**Issue by sirawatGG** [AndreiCalazans/hackernews-react-relay#2]
First of all, thank you for a great example for relay modern. 
I created graphCool server project and copy your project.graphcool to my graphCool types.graphql. Then I change "implements Node" to "@model". However, when I use command get-graphql-schema ENDPOINT_URL > schema.graphql, I don't receive signinUser in Mutation as well as type SigninUserInput, SigninPayload. Are these things manually written by you, or do I have to do something to generate them?

**Comment by AndreiCalazans** [comment]
Yes it was missing. Here is the issue I had opened up https://github.com/howtographql/howtographql/issues/178
